### ISSUE TITLE
The navbar links hang after clicking on demo

### ISSUE THREAD

**Issue by NiklasHae** [unpoly/unpoly-site#20] opened 2023-05-05 12:37 UTC
Hi :wave: 

I managed to break navigation when clicking on some navigation links. I get the following error log in the devconsole:
```
guide-e3a5a325.js:26 Uncaught (in promise) DOMException: Failed to execute 'matches' on 'Element': ':none' is not a valid selector.
    at up.Selector.matches (https://unpoly.com/javascripts/guide-e3a5a325.js:26:11013)
    at up.Selector.closest (https://unpoly.com/javascripts/guide-e3a5a325.js:26:11092)
    at Object.v [as closest] (https://unpoly.com/javascripts/guide-e3a5a325.js:26:26681)
    at up.FragmentFinder.findClosest (https://unpoly.com/javascripts/guide-e3a5a325.js:24:28996)
    at up.FragmentFinder.findAroundOrigin (https://unpoly.com/javascripts/guide-e3a5a325.js:24:28926)
    at up.FragmentFinder.find (https://unpoly.com/javascripts/guide-e3a5a325.js:24:28778)
    at f (https://unpoly.com/javascripts/guide-e3a5a325.js:26:26338)
    at Object.x [as reload] (https://unpoly.com/javascripts/guide-e3a5a325.js:26:27112)
    at e.revalidate (https://unpoly.com/javascripts/guide-e3a5a325.js:24:11772)
    at e.finish (https://unpoly.com/javascripts/guide-e3a5a325.js:24:11506)
matches @ guide-e3a5a325.js:26
closest @ guide-e3a5a325.js:26
v @ guide-e3a5a325.js:26
findClosest @ guide-e3a5a325.js:24
findAroundOrigin @ guide-e3a5a325.js:24
find @ guide-e3a5a325.js:24
f @ guide-e3a5a325.js:26
x @ guide-e3a5a325.js:26
revalidate @ guide-e3a5a325.js:24
finish @ guide-e3a5a325.js:24
Promise.then (async)
runResultCallbacks @ guide-e3a5a325.js:23
execute @ guide-e3a5a325.js:23
await in execute (async)
e @ guide-e3a5a325.js:23
(anonymous) @ guide-e3a5a325.js:26
(anonymous) @ guide-e3a5a325.js:27
(anonymous) @ guide-e3a5a325.js:27
nativeCallback @ guide-e3a5a325.js:24
dispatchEvent @ guide-e3a5a325.js:24
emit @ guide-e3a5a325.js:24
s @ guide-e3a5a325.js:26
x @ guide-e3a5a325.js:27
(anonymous) @ guide-e3a5a325.js:27
asCurrent @ guide-e3a5a325.js:25
asCurrent @ guide-e3a5a325.js:25
nativeCallback @ guide-e3a5a325.js:24
```

I can relatively stable reproduce the error in an incognito chrome by doing the following:

1. Open https://unpoly.com
2. Click slowly back and forth between "API" and "Tutorial" in the navbar
3. After around 15-20 clicks the above error shows in the console and the links are broken from now on

Let me know if you can't reproduce, need help or need more info :v:

**Comment by adam12** [comment] 2023-05-05 13:57
Thanks for reporting. I recall seeing this recently as well.

Out of curiosity, from what geographic location are you browsing from? When I saw it, it looked like async requests might have stacked up, since some of them were taking fairly long to respond. I _believe_ I'm on a different continent than the demo server and chalked it up to that. Be curious how far you might be from the server as well.

**Comment by adam12** [comment] 2023-05-05 13:59
Actually, it might be unrelated to distance, since in the log it shows Unpoly booting multiple times.

**Comment by triskweline** [comment] 2023-05-05 14:56
> since in the log it shows Unpoly booting multiple times.

Good catch.

With Unpoly 3 we've started to run scripts in updated fragments, and unpoly.com includes its application bundle within the `<body>`. When we go back in history, Unpoly updates the `<body>` from the previous URL and re-runs the application bundle.

**Comment by adam12** [comment] 2023-05-06 12:31
> since in the log it shows Unpoly booting multiple times.

Looking at this a bit deeper, it might not be the issue since Unpoly is loading in an `<iframe>` from the embed.

Here's the interaction log that I saw when I reproduced it.

```
up.hello() Compiling fragment <html up-source=​"/​examples/​update-fragment/​back.html">​…​</html>​
example-305e9b07.js:4 up:fragment:inserted Inserted fragment <html up-source=​"/​examples/​update-fragment/​back.html">​…​</html>​
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 mousedown Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:follow Following link
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 up.render() Skipping HTTP 304 response to GET /api
guide-e3a5a325.js:26 up.render() Nothing was rendered
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​tutorial" class=​"top_nav__section up-current" aria-current=​"page">​Tutorial​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​tutorial" class=​"top_nav__section up-current" aria-current=​"page">​Tutorial​</a>​
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /tutorial
guide-e3a5a325.js:26 mousedown Interaction on <a href=​"/​tutorial" class=​"top_nav__section up-current" aria-current=​"page">​Tutorial​</a>​
guide-e3a5a325.js:26 up:link:follow Following link
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /tutorial
guide-e3a5a325.js:26 up.render() Skipping HTTP 304 response to GET /tutorial
guide-e3a5a325.js:26 up.render() Nothing was rendered
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​version_choice" class=​"version_nav" up-layer=​"new popup" up-target=​".choice">​…​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​version_choice" class=​"version_nav" up-layer=​"new popup" up-target=​".choice">​…​</a>​
guide-e3a5a325.js:26 up:request:load Loading GET /version_choice
guide-e3a5a325.js:26 up:request:aborted Aborted request to GET /version_choice
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 mousedown Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:follow Following link
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 up.render() Skipping HTTP 304 response to GET /api
guide-e3a5a325.js:26 up.render() Nothing was rendered
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 mousedown Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:follow Following link
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 up.render() Skipping HTTP 304 response to GET /api
guide-e3a5a325.js:26 up.render() Nothing was rendered
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​up.popup.config" class=​"node__self ">​…​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​up.popup.config" class=​"node__self ">​…​</a>​
guide-e3a5a325.js:26 up:request:load Loading GET /up.popup.config
guide-e3a5a325.js:26 up:request:aborted Aborted request to GET /up.popup.config
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​up.radio" class=​"node__self ">​…​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​up.radio" class=​"node__self ">​…​</a>​
guide-e3a5a325.js:26 up:request:load Loading GET /up.radio
guide-e3a5a325.js:26 up:request:aborted Aborted request to GET /up.radio
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​up.fragment.config" class=​"node__self">​…​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​up.fragment.config" class=​"node__self">​…​</a>​
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /up.fragment.config
guide-e3a5a325.js:26 mouseenter Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:preload Preloading link <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 mousedown Interaction on <a href=​"/​api" class=​"top_nav__section" up-alias=​"/​up.* /​up:​* /​up-* /​*-up-* /​has">​API​</a>​
guide-e3a5a325.js:26 up:link:follow Following link
guide-e3a5a325.js:26 up.request() Re-using previous request to GET /api
guide-e3a5a325.js:26 up.render() Skipping HTTP 304 response to GET /api
guide-e3a5a325.js:26 up.render() Nothing was rendered
guide-e3a5a325.js:26 up.render() Revalidating cached response for target ":none"
guide-e3a5a325.js:26 Uncaught (in promise) DOMException: Failed to execute 'matches' on 'Element': ':none' is not a valid selector.
    at up.Selector.matches (https://unpoly.com/javascripts/guide-e3a5a325.js:26:11013)
    at up.Selector.closest (https://unpoly.com/javascripts/guide-e3a5a325.js:26:11092)
    at Object.v [as closest] (https://unpoly.com/javascripts/guide-e3a5a325.js:26:26681)
    at up.FragmentFinder.findClosest (https://unpoly.com/javascripts/guide-e3a5a325.js:24:28996)
    at up.FragmentFinder.findAroundOrigin (https://unpoly.com/javascripts/guide-e3a5a325.js:24:28926)
    at up.FragmentFinder.find (https://unpoly.com/javascripts/guide-e3a5a325.js:24:28778)
    at f (https://unpoly.com/javascripts/guide-e3a5a325.js:26:26338)
    at Object.x [as reload] (https://unpoly.com/javascripts/guide-e3a5a325.js:26:27112)
    at e.revalidate (https://unpoly.com/javascripts/guide-e3a5a325.js:24:11772)
    at e.finish (https://unpoly.com/javascripts/guide-e3a5a325.js:24:11506)
matches @ guide-e3a5a325.js:26
closest @ guide-e3a5a325.js:26
v @ guide-e3a5a325.js:26
findClosest @ guide-e3a5a325.js:24
findAroundOrigin @ guide-e3a5a325.js:24
find @ guide-e3a5a325.js:24
f @ guide-e3a5a325.js:26
x @ guide-e3a5a325.js:26
revalidate @ guide-e3a5a325.js:24
finish @ guide-e3a5a325.js:24
Promise.then (async)
runResultCallbacks @ guide-e3a5a325.js:23
execute @ guide-e3a5a325.js:23
await in execute (async)
e @ guide-e3a5a325.js:23
(anonymous) @ guide-e3a5a325.js:26
(anonymous) @ guide-e3a5a325.js:27
(anonymous) @ guide-e3a5a325.js:27
nativeCallback @ guide-e3a5a325.js:24
dispatchEvent @ guide-e3a5a325.js:24
emit @ guide-e3a5a325.js:24
s @ guide-e3a5a325.js:26
x @ guide-e3a5a325.js:27
(anonymous) @ guide-e3a5a325.js:27
asCurrent @ guide-e3a5a325.js:25
asCurrent @ guide-e3a5a325.js:25
nativeCallback @ guide-e3a5a325.js:24
```

**Comment by triskweline** [comment] 2023-05-10 15:38
This should be fixed now. Thanks for the analysis @adam12 @NiklasHae .

Although the multiple bootings came from the iframes on the tutorial, the site still re-executed the application bundle whenever going back or forward in history.

**Closed as completed by triskweline** 2023-05-10 15:38 UTC
